#!/usr/bin/env python3
"""Resolve complete hashed Windows runtime locks for Python 3.11 and 3.12."""

from __future__ import annotations

import argparse
import email.parser
import hashlib
import re
import subprocess
import sys
import tempfile
import zipfile
from dataclasses import dataclass
from pathlib import Path

from build_portable_runtime_wheels import build_all, sha256_file

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_REQUIREMENTS = REPO_ROOT / "packaging" / "portable" / "locks" / "requirements-runtime.in"
DEFAULT_OUTPUT_DIR = DEFAULT_REQUIREMENTS.parent
CANONICAL_NAME_PATTERN = re.compile(r"[-_.]+")


@dataclass(frozen=True)
class Target:
    """One CPython/Windows lock target."""

    abi: str
    python_version: str

    @property
    def lock_filename(self) -> str:
        """Return the repository lock filename for this target."""
        return f"requirements-runtime-{self.abi}-win-x64.lock"


TARGETS = (Target("py311", "3.11"), Target("py312", "3.12"))


def canonicalize_name(name: str) -> str:
    """Apply the package-name normalization used by Python packaging tools."""
    return CANONICAL_NAME_PATTERN.sub("-", name).lower()


def wheel_name_and_version(wheel: Path) -> tuple[str, str]:
    """Read the authoritative project name and version from wheel metadata."""
    with zipfile.ZipFile(wheel) as archive:
        metadata_files = [
            name for name in archive.namelist() if name.endswith(".dist-info/METADATA") and name.count("/") == 1
        ]
        if len(metadata_files) != 1:
            raise RuntimeError(f"Expected one METADATA file in {wheel.name}, found {len(metadata_files)}")
        metadata = email.parser.BytesParser().parsebytes(archive.read(metadata_files[0]))

    name = metadata.get("Name")
    version = metadata.get("Version")
    if not name or not version:
        raise RuntimeError(f"Missing Name or Version metadata in {wheel.name}")
    return canonicalize_name(name), version


def render_lock(target: Target, wheel_dir: Path) -> str:
    """Render one complete strict-hash lock from a resolved wheel directory."""
    entries: dict[str, tuple[str, str, str]] = {}
    wheels = sorted(wheel_dir.glob("*.whl"))
    if not wheels:
        raise RuntimeError(f"No wheels resolved for {target.abi}")

    for wheel in wheels:
        name, version = wheel_name_and_version(wheel)
        if name in entries:
            raise RuntimeError(f"Duplicate project {name} in {target.abi} wheelhouse")
        entries[name] = (version, sha256_file(wheel), wheel.name)

    header = [
        f"# BiliLiveCut Portable runtime dependency lock ({target.python_version}, Windows x64)",
        "# Complete transitive closure; every selected wheel is pinned and SHA-256 verified.",
        "# Generated by scripts/generate_portable_runtime_locks.py.",
        f"# Packages: {len(entries)}",
        "",
    ]
    lines = [
        f"{name}=={version} --hash=sha256:{digest}  # {filename}"
        for name, (version, digest, filename) in sorted(entries.items())
    ]
    return "\n".join(header + lines) + "\n"


def resolve_target(target: Target, requirements: Path, source_wheels: Path, wheel_dir: Path) -> None:
    """Resolve one Windows target to binary wheels only."""
    command = [
        sys.executable,
        "-m",
        "pip",
        "download",
        "--disable-pip-version-check",
        "--requirement",
        str(requirements),
        "--dest",
        str(wheel_dir),
        "--only-binary=:all:",
        "--platform",
        "win_amd64",
        "--python-version",
        target.python_version,
        "--implementation",
        "cp",
        "--abi",
        target.abi.replace("py", "cp"),
        "--find-links",
        str(source_wheels),
    ]
    subprocess.run(command, check=True)


def direct_requirement_names(requirements: Path) -> set[str]:
    """Return direct requirement names from the simple pinned input file."""
    names = set()
    for raw_line in requirements.read_text(encoding="utf-8").splitlines():
        line = raw_line.split("#", 1)[0].strip()
        if not line:
            continue
        name, separator, _version = line.partition("==")
        if not separator:
            raise RuntimeError(f"Direct runtime requirement must use ==: {raw_line}")
        names.add(canonicalize_name(name.split("[", 1)[0].strip()))
    return names


def verify_direct_requirements(requirements: Path, lock_text: str, target: Target) -> None:
    """Ensure the resolver did not omit any direct runtime dependency."""
    locked_names = {
        canonicalize_name(line.partition("==")[0])
        for line in lock_text.splitlines()
        if line and not line.startswith("#")
    }
    missing = direct_requirement_names(requirements) - locked_names
    if missing:
        raise RuntimeError(f"{target.abi} lock omitted direct requirements: {', '.join(sorted(missing))}")


def generate_locks(requirements: Path, output_dir: Path, cache_dir: Path) -> list[Path]:
    """Build source-only wheels, resolve both targets, and write complete locks."""
    if not requirements.is_file():
        raise RuntimeError(f"Requirements input not found: {requirements}")
    output_dir.mkdir(parents=True, exist_ok=True)

    generated: list[Path] = []
    with tempfile.TemporaryDirectory(prefix="blc-runtime-locks-") as temporary:
        work_dir = Path(temporary)
        source_wheels = work_dir / "source-wheels"
        build_all(source_wheels, cache_dir)

        for target in TARGETS:
            wheel_dir = work_dir / target.abi
            wheel_dir.mkdir()
            print(f"Resolving {target.abi} Windows wheel closure")
            resolve_target(target, requirements, source_wheels, wheel_dir)
            lock_text = render_lock(target, wheel_dir)
            verify_direct_requirements(requirements, lock_text, target)
            lock_path = output_dir / target.lock_filename
            lock_path.write_text(lock_text, encoding="utf-8", newline="\n")
            generated.append(lock_path)
            print(f"Wrote {lock_path} ({len(list(wheel_dir.glob('*.whl')))} packages)")

    combined = hashlib.sha256()
    for path in generated:
        combined.update(path.read_bytes())
    print(f"Combined lock SHA-256: {combined.hexdigest()}")
    return generated


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--requirements", type=Path, default=DEFAULT_REQUIREMENTS)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--cache-dir", type=Path, default=Path(".cache/portable-runtime-sdists"))
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    """Generate both portable Windows runtime locks."""
    args = parse_args(argv)
    generate_locks(args.requirements.resolve(), args.output_dir.resolve(), args.cache_dir.resolve())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
