"""设置注册表的中文名称；技术键与名称一起用于搜索。"""

LABELS: dict[str, str] = {
    "scoring_configuration": "评分权重、融合、窗口与去重",
    "storage_cleanup_enabled": "按保留策略自动清理原片（默认关闭）",
    "max_analyzing": "同时分析任务数",
    "max_rendering": "同时渲染任务数",
    "max_publishing": "同时投稿任务数",
    "worker_shutdown_timeout_seconds": "后台任务关闭等待时间",
    "stale_timeout_s": "失联任务回收时间",
    "upload_attempt_stale_s": "未返回上传结果确认时间",
    "low_disk_threshold_gb": "暂停新任务的磁盘阈值",
    "critical_disk_threshold_gb": "停止录制的紧急磁盘阈值",
    "app_env": "运行环境",
    "log_level": "日志级别",
    "admin_password": "管理员密码",
    "reviewer_accounts_json": "审核员账号",
    "review_claim_ttl_s": "审核领取有效期",
    "review_blind_mode": "盲审",
    "storage_root": "存储根目录",
    "database_url": "数据库连接",
    "plugin_dir": "插件目录",
    "ffmpeg_path": "FFmpeg 程序路径",
    "ffprobe_path": "FFprobe 程序路径",
    "segment_duration_s": "录制分段目标时长",
    "preferred_stream_protocol": "首选直播流协议",
    "stream_quality": "直播流画质编号",
    "reconnect_max_backoff_s": "重连最长退避",
    "live_poll_interval_s": "直播状态检查间隔",
    "room_metadata_refresh_interval_s": "直播标题刷新间隔",
    "room_metadata_refresh_timeout_s": "标题查询超时",
    "recording_reconnect_max_attempts": "断流最大重试次数（0 不限制）",
    "recording_reconnect_max_elapsed_s": "断流重试最长时间（0 不限制）",
    "live_offline_confirm_count": "下播连续确认次数",
    "live_session_end_delay_s": "下播收尾延迟",
    "recording_max_duration_s": "单场录制时长上限",
    "collect_danmaku": "采集弹幕",
    "danmaku_login_retry_max_attempts": "弹幕登录最多尝试次数",
    "danmaku_login_retry_interval_s": "弹幕登录重试间隔",
    "recording_pipeline_enabled": "录制后自动转写与分析",
    "require_authorization": "要求直播间授权",
    "bilibili_cookie": "Bilibili Cookie",
    "whisper_model": "Whisper 模型",
    "whisper_device": "Whisper 默认设备",
    "whisper_compute_type": "Whisper 计算精度",
    "asr_resource_policy": "模型资源不足处理",
    "asr_primary": "ASR 主引擎",
    "asr_sensevoice": "加载 SenseVoice 辅助模型",
    "asr_funasr_review": "FunASR 低质量复核",
    "asr_fallback_whisper": "Whisper 兜底",
    "asr_confidence_threshold": "旧版置信度阈值",
    "asr_review_risk_threshold": "复核风险阈值",
    "asr_sensevoice_enabled": "使用 SenseVoice 辅助特征",
    "asr_vad_max_segment_s": "语音活动切句上限",
    "asr_task_max_concurrency": "同时转写任务数",
    "asr_model_idle_unload_seconds": "非驻留模型空闲卸载时间（0 关闭）",
    "asr_preload_on_start": "启动预加载模型",
    "asr_model_revision": "旧版全局模型版本",
    "llm_daily_budget": "LLM 每日预算（美元，0 不限）",
    "transcript_llm_refine_enabled": "LLM 整理转写与摘要",
    "transcript_llm_refine_max_tokens": "转写整理输出 Token 上限",
    "highlight_llm_max_tokens": "高光复核输出 Token 上限",
    "hotspot_enrichment_llm_max_tokens": "热点解释输出 Token 上限",
    "trend_enabled": "启用网感资料库",
    "trend_api_key": "网感专用 API 密钥",
    "trend_base_url": "网感专用服务地址",
    "trend_model": "网感专用模型",
    "trend_web_search_param": "联网搜索参数名",
    "trend_web_search": "启用联网搜索",
    "trend_max_items": "每次网感条目上限",
    "trend_retention_days": "网感资料保留天数",
    "trend_match_days": "近期网感匹配天数",
    "highlight_init_threshold": "高光初筛阈值",
    "highlight_threshold": "高光入选阈值",
    "highlight_review_threshold": "进入人工审核阈值",
    "highlight_auto_approve_threshold": "高光自动通过阈值",
    "highlight_max_candidates_per_segment": "每分段候选上限",
    "highlight_peak_min_distance_s": "高光峰值最小间距",
    "highlight_min_pre_roll_s": "成片最短前置留白",
    "highlight_min_post_roll_s": "成片最短后置留白",
    "danmaku_event_lag_s": "弹幕事件延迟补偿",
    "hotspot_bucket_s": "热点统计桶时长",
    "hotspot_baseline_window_s": "热点滚动基线窗口",
    "hotspot_detector_tick_s": "热点检测间隔",
    "hotspot_min_baseline_buckets": "热点最少基线桶数",
    "hotspot_detection_threshold": "热点检测阈值",
    "hotspot_event_merge_gap_s": "热点合并间隔",
    "hotspot_event_confirm_delay_s": "热点稳定确认延迟",
    "hotspot_event_semantic_overlap_threshold": "热点语义重叠阈值",
    "hotspot_recording_gap_tolerance_s": "录制连续性容差",
    "hotspot_asr_enabled": "热点优先局部转写",
    "hotspot_asr_pre_roll_s": "热点转写前置窗口",
    "hotspot_asr_post_roll_s": "热点转写后置窗口",
    "hotspot_asr_priority": "热点转写优先级",
    "near_live_asr_priority": "实时转写优先级",
    "background_asr_priority": "历史转写优先级",
    "auto_publish_threshold": "自动发布分数阈值",
    "clip_loudnorm": "响度标准化",
    "clip_remove_silence": "去除首尾静音",
    "clip_vertical": "竖屏输出",
    "clip_subtitle": "烧录字幕",
    "clip_max_duration_s": "成片时长上限",
    "clip_video_crf": "视频 CRF 质量（越小越清晰）",
    "clip_preset": "视频编码速度档",
    "threshold_learning_min_samples": "阈值学习最少反馈",
    "threshold_learning_max_delta": "阈值学习单次调整上限",
    "schedule_check_interval_s": "预约检查间隔",
    "auto_recover_max_age_hours": "启动恢复回溯小时数",
    "min_free_disk_gb": "高风险任务最低空闲空间",
    "raw_retention_days": "原始录像保留天数",
    "clip_cleanup_delay_hours": "生成成片后的原始分段清理延迟",
    "uploader": "旧版上传器默认值",
    "upload_max_retries": "上传最大重试次数",
    "upload_max_per_hour": "每小时上传上限",
    "title_max_len": "投稿标题字数上限",
    "desc_max_len": "投稿简介字数上限",
    "biliup_config": "biliup 配置文件路径",
    "biliup_upload_cmd": "biliup 上传命令模板",
    "notify_enabled": "启用通知",
    "dingtalk_webhook": "钉钉 Webhook",
    "dingtalk_secret": "钉钉签名密钥",
    "wecom_webhook": "企业微信 Webhook",
    "smtp_host": "SMTP 服务器",
    "smtp_port": "SMTP 端口",
    "smtp_user": "SMTP 用户名",
    "smtp_password": "SMTP 密码",
    "smtp_from": "邮件发件人",
    "smtp_to": "邮件收件人（逗号分隔）",
    "notify_on_clip": "成片完成通知",
    "notify_on_upload": "投稿完成通知",
    "notify_on_disk_alert": "磁盘不足通知",
    "notify_on_error": "任务失败通知",
    "disk_alert_threshold_gb": "磁盘通知阈值",
    "biliup_enabled": "启用 biliup 投稿",
    "auto_upload": "成片自动加入投稿队列",
    "trend_schedule_enabled": "启用网感定时采集",
    "trend_schedule_start": "网感采集开始时间",
    "trend_schedule_end": "网感采集结束时间",
    "trend_schedule_interval_min": "网感采集间隔（分钟）",
    "threshold_learning_enabled": "全局阈值学习",
    "danmaku_sentiment_enabled": "全局弹幕情绪分析",
}
for _role, _name in {
    "primary": "主引擎",
    "auxiliary": "辅助引擎",
    "review": "复核引擎",
    "fallback": "兜底引擎",
}.items():
    LABELS[f"asr_{_role}_device"] = f"{_name}设备"
    LABELS[f"asr_{_role}_max_concurrency"] = f"{_name}最大并发"
    LABELS[f"asr_{_role}_keep_loaded"] = f"{_name}模型常驻"
